### ISSUE TITLE
Feature: canvas click event

### ISSUE THREAD

**Issue by KYHyeon** [KYHyeon/madgo#21]
Canvas의 클릭 이벤트 처리 방법
캔버스 내부 도형에 클릭 이벤트를 추가하는 것은 불가능하다.

해결방안
1. 캔버스 내부에 그려진 도형 범위를 기억하기
2. 도형마다 다른 색을 부여하고 이를 확인하기

https://webisfree.com/2018-05-31/[html5]-canvas-%EC%9A%94%EC%86%8C%EC%9D%98-%EB%8F%84%ED%98%95%EC%97%90-%ED%81%B4%EB%A6%AD-%EC%9D%B4%EB%B2%A4%ED%8A%B8-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

어떤 방법이 더 나아 보이나요?

**Comment by limyeonsoo** [comment]
저는 1번 방법이 좋을 것 같습니다.
아무래도 반응형 웹이 대세인데, 비율만 선정해놓는다면 실행한 화면의 크기에 따라서 영역을 구분할 수 있을 것 같습니다. 
더군다나, 저희가 구현하려는 것은 카드가 특정 영역에서 특정 영역으로만 이동을 하기 때문에 더 좋은 방법론인 것 같습니다.
2번 방법은 다른 색을 부여해야하는데, 머릿속으로 잠시 생각을 해봐도 카드의 움직임에 필요한 경우의 수가 많이 떠오르는 군요. 제 생각엔 2번 방법은 어울리지 않는 것 같습니다.

**Comment by KYHyeon** [comment]
그러면 1. 캔버스 내부에 그려진 도형 범위를 기억하기 이렇게 구현하는걸로 하겠습니다.
